version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    expose:
      - "9000"

  back-end:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    expose:
      - "5252"
    deploy:
      replicas: 2

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end